### ISSUE TITLE
When comparing schedulers, take into accunt that the current scheduler is artificially better than shadow schedulers

### ISSUE THREAD

**Issue by marco-c** [mozilla/ci-recipes#14]
If the currently used scheduler only schedules win64/opt-mochitest-1 and the shadow scheduler would have scheduled linux64/opt-mochitest-1 it is considered as an error, but it shouldn’t.

Restricting the scheduler evaluation on the pushes where we run all jobs would solve this, as we could really see if the shadow scheduler at least scheduled one of the failing jobs. The problem is that we reduce the amount of data on which we run the evaluation.

Perhaps the best solution is to evaluate both on all pushes and on the subset of pushes where we run all jobs, to have an idea of the difference.

**Comment by ahal** [comment]
This is now being handled in mozci.

**Comment by marco-c** [comment]
Moved to https://github.com/mozilla/cia-tasks/issues/6.
