### ISSUE TITLE
Make push.py usable by other projects or make recipes executable easily (e.g. as console_scripts)

### ISSUE THREAD

**Issue by marco-c** [mozilla/ci-recipes#3]
I'd like to use the push.py module in another project, right now I need to copy it.
I'm not sure if it makes sense to publish ci-recipes on PyPI or if we should create another project with libraries such as push.py and make ci-recipes import that.

**Comment by ahal** [comment]
Done:
https://github.com/mozilla/mozci/tree/master/mozci
